### ISSUE TITLE
Error after downloading

### ISSUE THREAD

**Issue by farfary** [7aman/zsub#16]
Hi,
i have an error after downloading finished, i think this happend when unzip a file

```
FMBP:bin farhad$ python3 zsub dl -a -l fa en -t /Volumes/Farhad\ MHD/Friends/Friends.S01E01.1080p_IFR/Friends.S01E01.1080p_IFR.mkv
[subscene] https://subscene.com is OK
[Search] https://subscene.com/subtitles/searchbytitle
[Select]
   1 - Friends - First Season (1994)
   2 - Friends - Second Season (1995)
   3 - Friends - Third Season (1996)
   4 - Friends - Seventh Season (2000)
   5 - Friends - Sixth Season (1999)
   6 - Friends - Ninth Season (2002)
   7 - Friends - Fourth Season (1997)
   8 - Friends - Eighth Season (2000)
   9 - Friends - Fifth Season (1998)
  10 - Isshuukan Friends (One Week Friends) (2014)
  11 - Beaches AKA Forever Friends (1988)
  12 - Your Friends & Neighbors (1998)
  ....auto select....
      "Friends - First Season (1994)"
      "https://subscene.com/subtitles/friends--first-season"
[Filters]
  1) Languages:
      farsi_persian(fa): 264
      english(en): 62
  2) remove duplicates: 326 -> 191
  3) remove downloaded: 191 -> 3

## total: 3 subtitles to download

[Get Links]
  [1/3] https://subscene.com/subtitles/friends--first-season/english/539099
  [2/3] https://subscene.com/subtitles/friends--first-season/farsi_persian/563934
  [3/3] https://subscene.com/subtitles/friends--first-season/farsi_persian/218659
[Download]
  [1/3] /Users/farhad/.zsub/cache/subtitles/friends--first-season/english/539099.zip
  [2/3] /Users/farhad/.zsub/cache/subtitles/friends--first-season/farsi_persian/563934.zip
  [3/3] /Users/farhad/.zsub/cache/subtitles/friends--first-season/farsi_persian/218659.zip
[Extract]
 [1] /Users/farhad/.zsub/cache/subtitles/friends--first-season/english/539099.zip
    ...zip file is corrupted. delete...
    ...downloaded from: https://subscene.com/subtitles/friends--first-season/english/539099
 [2] /Users/farhad/.zsub/cache/subtitles/friends--first-season/farsi_persian/563934.zip
    ...zip file is corrupted. delete...
    ...downloaded from: https://subscene.com/subtitles/friends--first-season/farsi_persian/563934
 [3] /Users/farhad/.zsub/cache/subtitles/friends--first-season/farsi_persian/218659.zip
    ...zip file is corrupted. delete...
    ...downloaded from: https://subscene.com/subtitles/friends--first-season/farsi_persian/218659
Traceback (most recent call last):
  File "zsub", line 10, in <module>
    sys.exit(main())
  File "/Users/farhad/Library/Python/3.7/lib/python/site-packages/zsub/__init__.py", line 22, in main
    dl(req)
  File "/Users/farhad/Library/Python/3.7/lib/python/site-packages/zsub/commands/dl.py", line 20, in dl
    remove_same(req.unzip)
  File "/Users/farhad/Library/Python/3.7/lib/python/site-packages/zsub/common/utils.py", line 162, in remove_same
    files = [{'file': file, 'md5': md5(file.read_bytes()).digest()} for file in path.iterdir()]
  File "/Users/farhad/Library/Python/3.7/lib/python/site-packages/zsub/common/utils.py", line 162, in <listcomp>
    files = [{'file': file, 'md5': md5(file.read_bytes()).digest()} for file in path.iterdir()]
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1192, in read_bytes
    with self.open(mode='rb') as f:
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
IsADirectoryError: [Errno 21] Is a directory: '/Users/farhad/Downloads/zsub/Season 2'
FMBP:bin farhad$ 
```

**Comment by 7aman** [comment]
Hi @farfary.
Sorry for late response.
I wrongly assumed uploaded zip files to subscene.com have only files on their root path and do not contain any folders.
There is a problem with digesting hash for items in destination folder.
I will patch it to skip hashing folders in destination.

**Comment by 7aman** [comment]
You can check it out by installing from repo
```shell
pip3 install  --user --upgrade git+https://github.com/7aman/zsub.git
```
or wait until next release and upgrade with pip.
```shell
pip3 install --user -U zsub
```

**Comment by 7aman** [comment]
and one suggestion:
`-t` switch takes some keywords and not a file path. It is better to use it this way:
```shell
zsub dl -a -l en fa -s subscene -t friends first season
```

**Comment by 7aman** [comment]
I fixed this error. Please update to the latest version:
```shell
pip3 install --user -U zsub
```
